site_name: MAestro Documentation
site_description: Meta-Analysis Extraction, Synthesis, and Transparency Research Orchestrator
site_author: MAestro Contributors
site_url: https://maestro-meta.github.io

repo_name: wmerzhan/meta
repo_url: https://github.com/wmerzhan/meta
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: quickstart.md
      - Development Setup: ../DEVELOPMENT_SETUP.md
  - Documentation:
      - Best Practices: best-practices.md
      - Architecture: architecture.md
  - Success Stories:
      - Cardiovascular Risk Factors: case-studies/cardiovascular-risk-factors.md
      - K-12 Literacy Interventions: case-studies/literacy-interventions-novice-user.md
      - Climate Intervention Evidence Synthesis: case-studies/climate-intervention-exploration.md
  - API Reference:
      - API Overview: api/index.md
  - Community:
      - Contributing: ../CONTRIBUTING.md
  - Launch:
      - Community Launch Plan: launch/community-launch-plan.md
      - Launch Metrics Dashboard: launch/metrics-dashboard.md
      - Methodology Preprint Outline: launch/methodology-preprint.md
      - Testimonials & Credibility Signals: launch/testimonials.md
      - Post-Launch Support Plan: launch/support-plan.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wmerzhan/meta
  version:
    provider: mike

copyright: Copyright &copy; 2025 MAestro Contributors
