name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Python linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff mypy

      - name: Run black
        run: black --check scripts

      - name: Run ruff
        run: ruff check scripts

      - name: Run mypy
        run: mypy scripts
