name: Tests

# Triggered by pushes to main and pull requests. Re-run from the Actions tab after fixing failures.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run test suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.11"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install Poetry (future CLI support)
        run: python -m pip install poetry

      - name: Install lint tooling
        run: python -m pip install black ruff mypy

      - name: Run pytest (if tests are present)
        shell: bash
        run: |
          python - <<'PY'
          from pathlib import Path
          import subprocess
          import sys

          test_root = Path("tests")
          test_files = [path for path in test_root.rglob("test_*.py") if path.is_file()]

          if not test_files:
              print("No pytest-compatible tests detected; skipping pytest execution.")
              sys.exit(0)

          result = subprocess.run([sys.executable, "-m", "pytest"], check=False)
          sys.exit(result.returncode)
          PY

      - name: Run black
        run: black --check scripts

      - name: Run ruff
        run: ruff check scripts

      - name: Run mypy
        run: mypy scripts
