name: Validate Prompts

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "prompts/**"
      - "scripts/ci/validate_prompts.py"
      - ".github/workflows/validate-prompts.yml"

jobs:
  validate:
    name: Prompt metadata check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run prompt validator
        run: python scripts/ci/validate_prompts.py
